# Generated by Django 5.2.7 on 2025-12-18 04:43

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('nairobi_peak', 'Nairobi Peak Hour'), ('nakuru_central', 'Nakuru Central'), ('mombasa_coastal', 'Mombasa Coastal'), ('kisumu_lakeside', 'Kisumu Lakeside')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(choices=[('baseline', 'Baseline (Current)'), ('rl_optimized', 'Reinforcement Learning'), ('ga_optimized', 'Genetic Algorithm'), ('hybrid', 'Hybrid AI')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('progress', models.FloatField(default=0.0)),
                ('current_epoch', models.IntegerField(default=0)),
                ('total_epochs', models.IntegerField(default=100)),
                ('current_loss', models.FloatField(blank=True, null=True)),
                ('current_accuracy', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_travel_time', models.FloatField(help_text='Minutes')),
                ('baseline_avg_travel_time', models.FloatField()),
                ('improvement_travel_time', models.FloatField(help_text='Percentage improvement')),
                ('total_delay', models.FloatField(help_text='Hours')),
                ('baseline_total_delay', models.FloatField()),
                ('delay_reduction', models.FloatField(help_text='Percentage reduction')),
                ('fuel_consumed', models.FloatField(help_text='Liters')),
                ('baseline_fuel_consumed', models.FloatField()),
                ('fuel_saving', models.FloatField(help_text='Percentage saving')),
                ('co2_emissions', models.FloatField(help_text='kg CO2')),
                ('baseline_co2_emissions', models.FloatField()),
                ('emissions_reduction', models.FloatField(help_text='Percentage reduction')),
                ('training_loss', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('training_accuracy', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('validation_loss', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('validation_accuracy', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('csv_data', models.TextField(blank=True, help_text='CSV formatted data')),
                ('pdf_report_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('travel_time', 'Average Travel Time'), ('delay', 'Total Delay'), ('fuel', 'Fuel Consumption'), ('emissions', 'CO2 Emissions'), ('speed', 'Average Speed'), ('congestion', 'Congestion Level')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('improvement_percentage', models.FloatField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.simulation')),
            ],
            options={
                'ordering': ['metric_type', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.simulation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.simulation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comparisons', to='core.simulation')),
                ('baseline_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_comparisons', to='core.simulation')),
            ],
            options={
                'unique_together': {('baseline_simulation', 'ai_simulation')},
            },
        ),
    ]
