# Generated by Django 5.2.7 on 2025-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=models.TextField(blank=True, default='{}', help_text='Enter valid JSON format'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='parameters',
            field=models.TextField(blank=True, default='{}', help_text='JSON parameters for the simulation'),
        ),
    ]
